image: Visual Studio 2017

environment:
  matrix:
    # stable x86_64 with static libsodium from binary release
  - TARGET: x86_64-pc-windows-msvc
    RUST_CHANNEL: stable
    RUST_BACKTRACE: 1

    # stable x86 with static libsodium from binary release
  - TARGET: i686-pc-windows-msvc
    RUST_CHANNEL: stable
    RUST_BACKTRACE: 1

  # stable x86_64 with static libsodium from binary release
  - TARGET: x86_64-pc-windows-gnu
    RUST_CHANNEL: stable
    RUST_BACKTRACE: 1

    # stable x86_64 with static libsodium from binary release
  - TARGET: x86_64-pc-windows-msvc
    RUST_CHANNEL: stable
    RUST_BACKTRACE: 1

install:
  - git submodule update --init --recursive
  - ps: |
      # Install Rust
      appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
      cmd.exe /c .\rustup-init.exe -y --profile minimal --default-host "$env:TARGET" --default-toolchain "$env:RUST_CHANNEL" 2`>`&1
      $env:PATH += ";$env:USERPROFILE\.cargo\bin"

      If ($env:SODIUM_USE_PKG_CONFIG -eq '1') {
        # Install libsodium via vcpkg
        vcpkg install "libsodium:$env:VCPKG_TARGET"
      }
  # Add GCC to PATH if needed.
  - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw64\bin

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

build: false
test_script:
  - cargo test --all --target %TARGET%
  - cargo test --all --release --target %TARGET%
